language: erlang
install: true
env:
  - PATH=".:$PATH"
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - sudo echo "#!/usr/bin/env bash" > `which rebar`
script: make check
otp_release:
  - 18.2
  - 17.5
  - R16B03-1
  - R15B03
